modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Patbox/sgui/issues"
license="LGPLv3"

[[mods]]
modId="sgui"
version="${version}"
displayName="Server GUI"
displayURL="https://github.com/Patbox/sgui/releases"
logoFile="icon.png"
authors="Patbox,aws404"
description='''Library for creating server side guis!'''
displayTest="IGNORE_ALL_VERSION"

[[mixins]]
    config="sgui.mixins.json"

[[dependencies.sgui]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sgui]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,)"
    ordering="NONE"
    side="BOTH"