package com.leclowndu93150.guichess.chess.util;

public enum GameState {
    WAITING_FOR_OPPONENT,
    WHITE_TURN,
    BLACK_TURN,
    WHITE_PROMOTION,
    BLACK_PROMOTION,
    CHECK_WHITE,
    CHECK_BLACK,
    CHECKMATE_WHITE_WINS,
    CHECKMATE_BLACK_WINS,
    STALEMATE,
    DRAW_AGREED,
    DRAW_FIFTY_MOVE,
    DRAW_THREEFOLD,
    DRAW_INSUFFICIENT,
    WHITE_RESIGNED,
    BLACK_RESIGNED,
    WHITE_TIME_OUT,
    BLACK_TIME_OUT,
    ABANDONED
}
